# Change these first
owner: richardtape # Your GitHub username
repo: ubcupptime # Your Github repository name

# Add your sites here
sites:
  - name: CMS
    url: https://cms.ubc.ca
  - name: Blogs
    url: https://blogs.ubc.ca
  - name: CTLT Events
    url: https://events.ctlt.ubc.ca
  - name: CourseSpaces
    url: https://coursespaces.ubc.ca/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  baseUrl: /ubcupptime
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UBC Uptime
  introTitle: "CTLT WordPress Instance Public Uptime Monitoring"
  introMessage: "Real-time Monitoring of UBC CMS, UBC Blogs, UBC CTLT Events, and UBC CourseSpaces environments."
  navbar:
    - title: Status
      href: /
    - title: CMS
      href: https://cms.ubc.ca
    - title: Blogs
      href: https://blogs.ubc.ca
    - title: CTLT Events
      href: https://events.ctlt.ubc.ca
    - title: CourseSpaces
      href: https://coursespaces.ubc.ca

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
